In [1]:
import numpy as np

Creating diffrerent types of arrays

In [3]:
#1D array
array_1 = np.array([1, 2, 3, 4])
print(array_1)

[1 2 3 4]


In [4]:
type(array_1)

numpy.ndarray

In [5]:
#2D array
array_2 = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2)

[[1 2 3]
 [4 5 6]]


In [6]:
#3D array
array_3 = np.array([[[1, 2, 3], [4, 5, 6]], [[11, 12, 13], [14, 15, 16]]])
print(array_3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


**Printing the data about the arrays**

In [11]:
#printing the array memory address
print(array_1.data)

In [14]:
#printing the array's datatype
print(array_2.dtype)

int32


In [15]:
#printing array's strides
print(array_3.strides)

(24, 12, 4)


In [16]:
#printing array's shape
print(array_3.shape)

(2, 2, 3)


Filling arrays

In [18]:
#filling with ones 
print(np.ones((5,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
#filling with zeros
print(np.zeros((2, 3, 3)))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [23]:
#Filling with some values -> ex : Filling with value 45
print(np.full((5, 6), 45))

[[45 45 45 45 45 45]
 [45 45 45 45 45 45]
 [45 45 45 45 45 45]
 [45 45 45 45 45 45]
 [45 45 45 45 45 45]]


In [38]:
#arranging values for a array form 10 to 20 with incremental value 5
print(np.arange(10, 20, 5))

[10 15]


In [39]:
#printing the values for a array from  50 to 5 with decremental value -10
print(np.arange(50, 5, -10))

[50 40 30 20 10]


In [40]:
#Array from 2 and 5 with 10 numbers equally between the interval (2, 5)
print(np.linspace(2, 5, 10))

[2.         2.33333333 2.66666667 3.         3.33333333 3.66666667
 4.         4.33333333 4.66666667 5.        ]
